### ISSUE TITLE
sinserv .config file never gets updated, if erlware installed to a different directory

### ISSUE THREAD

**Issue by sdurham** [erlware-deprecated/sinan#24]
the ~/.sinan/config/sinserv-<version>.config
file never changes.

I've been repeatedly pulling the entire erlang system into different
directories:
~/erlang
~/erw
~/ew2

etc etc.

I'm currently in ~/erw (erlware is at ~/erw/erlware).
I've been updating .bashrc to put ~/erw/erlware/bin
So everything seems to work,
but apparently sinserv has been checking against ~/erlang..., my
original install location.
I deleted that config file, re-ran sinan and it works fine.

I'd still like to know how to step in to sinan though, so I can track
this stuff down faster -- also, maybe there can be a verbose logging
flag so that sinan can tell me exactly what it thinks it is doing.

**Comment by sdurham** [comment]
See this thread:
http://groups.google.com/group/erlware-questions/browse_thread/thread/397bbcd95eb431a6

**Comment by ericbmerritt** [comment]
In the latest version, the config is going away completely. This should solve that particular problem.

**Comment by ericbmerritt** [comment]
this is resolved in the latest version of sinan 0.19.0.0
