### ISSUE TITLE
Command-line task override does not work

### ISSUE THREAD

**Issue by ericbmerritt** [erlware-deprecated/sinan#4]
What steps will reproduce the problem?
1. sinan task:build:compile_args="+debug_info -W1"

What is the expected output? What do you see instead?

efine@ender:~/work/integrat/xhg/otp$ sinan
task:build:compile_args="+debug_info -W1"
Usage: sinan [options] [task [server-variable server-value ...]]

Server arguments (pairs of variable and values) are complex. There are
always sane defaults so you shouldn't need them, but you may. To get
information about server arguments read the sinan documentation.

sinan: error: no such option: -W

What version of the product are you using? On what operating system?
0.10.0.14

Please provide any additional information below.

**Comment by efine** [comment]
I know what this is caused by - it's the insane Python command-line parsing library that doesn't allow spaces.

**Comment by ericbmerritt** [comment]
No that the book is getting close to being done I am expecting to have more time to work on this stuff. I will see if I can dig into this soon. I have a couple of higher priority issues.

**Comment by efine** [comment]
My solution to this in my sinan fork is to replace the spaces with colons, as I said in a different comment (it's in commit http://github.com/efine/sinan/commit/87867b6890beb010721fd13d7c09972f92b96e3a). It's not a perfect solution, though, because you still can't handle paths containing spaces and other joys like that.

**Comment by ericbmerritt** [comment]
This is resolved in the current sinan.

**Comment by ericbmerritt** [comment]
This is resolved in the current sinan.
