### ISSUE TITLE
single application project generation crashes

### ISSUE THREAD

**Issue by aeh** [erlware-deprecated/sinan#40]
Answering "yes" to the "Is this a single application project" question fails.
The /app/doc directory is being created twice - once in the build_out_skeleton function and again in the build_out_application function which dies with an eexists error.

{"init terminating in do_boot",{function_clause,[{sin_task_gen,is_made,["/app/doc",{error,eexist}]},{sin_task_gen,make_dir,1},{sin_task_gen,build_out_application,4},{sin_task_gen,build_out_applications,1},{sin_task_gen,get_project_information,2},{lists,foldl,3},{sinan,run_task,3},{sinan,do_task,3}]}}

**Comment by ericbmerritt** [comment]
Can you tell me what version of sinan you are using? (sinan version will tell you). And the platform you are running on?

**Comment by aeh** [comment]
sinan version: 0.24.0
Ubuntu 10.04.1

**Comment by aeh** [comment]
The problem is that in the case of a single application the AppDir and ProjDir are the same.  build_out_skeleton creates the ProjDir/doc/ directory and then the build_out_application attempts to create the same directory under the guise of AppDir/doc/ and fails due to it already existing.

Can be fixed by replacing the doc folder creation in either of the following functions (in sin_task_gen.erl) with...

build_out_skeleton/1
    case get_env(single_app_project, Env) of
        false -> make_dir(filename:join(ProjDir, "doc"));
        true -> noop
    end

or build_out_application/4
    case get_env(project_dir, Env) of
        AppDir -> noop;
        _ -> make_dir(filename:join(AppDir, "doc"))
    end

**Comment by jwilberding** [comment]
What is the latest status on this?

**Comment by ericbmerritt** [comment]
That shouldn't blue up though, with that failure and doesn't in other cases. Aeh, let me look into this and I will get a fix out. At the very least I can remove that problem.

**Comment by ericbmerritt** [comment]
Ok, this is fixed in my repo. It should be pushed and available in the next day or so

**Comment by jwilberding** [comment]
Sinan 0.26.1 has been published which fixes this problem.
