### ISSUE TITLE
rebar based dependency resolver

### ISSUE THREAD

**Issue by ericbmerritt** [erlware-deprecated/sinan#43]
suggested by @yrashk

**Comment by yrashk** [comment]
+1

**Comment by tmcgilchrist** [comment]
Are there any ideas on how you'd like this to work?

The rebar approach seems to work well in my limited experience. 
Would u be against someone porting a basic version of that across to sinan? Assuming I can get sinan building from source.

**Comment by ericbmerritt** [comment]
Sinan will probably be deprecated in the long term. The dependency solving features of sinan have been moved out to a new project called relcool that is independent of the build features of sinan. That is where future development on the solver will happen.
