### ISSUE TITLE
Make it an option to include erts into the build as a symlink, not a copy

### ISSUE THREAD

**Issue by yrashk** [erlware-deprecated/sinan#62]
Useful for local non-production builds (faster)

**Comment by ericbmerritt** [comment]
I think jordan is planning one small change to this, hopefully he can include this change as well when he is in there working

**Comment by ericbmerritt** [comment]
I suggest we change the option {include_erts, boolean()}. to be {include_erts, copy | symlink | none} or something to that effect

**Comment by yrashk** [comment]
Makes sense!

**Comment by jwilberding** [comment]
So, I am wondering, while I am at this, should I give the option to allow the user to specify which version of erts?

**Comment by yrashk** [comment]
Shouldn't it always be the one he's building with?

**Comment by jwilberding** [comment]
Yeah, I thought at one time we wanted to make the configurable as well as an argument to sinan.
