### ISSUE TITLE
Provide more control over sinan doc results

### ISSUE THREAD

**Issue by CarlWright** [erlware-deprecated/sinan#65]
Add the ability to include an item to the sinan.config file which defines the options to edoc when doing "SINAN DOC".

You could call the config entry "edoc_options".

This config item defines the proplist that is included in the call to edoc. The defined proplist is added to the default one that defines the destination of the results [".docs"] except when a property is "doc". In the event that the config proplist includes "dir", the "dir" supercedes the default value.

I'd use it to define the stylesheet to use and the version number of the documented package.

So I'd include  {edoc_options, [{def,{version,"2.6"}},{stylesheet_file, ".//doc/eg_stylesheet.css"}]}.

Carl

**Comment by ericbmerritt** [comment]
I have implemented this carl. I will get it tested and pushed out in the next couple of days

**Comment by CarlWright** [comment]
Thanks.... I'll use it and report back the results. We might encounter
un-intended consequences.

Carl 

-----Original Message-----
From: Eric Merritt
[mailto:reply+i-2697678-d27901824eebb658f87fea31516d6285a9b6b030-120615@
reply.github.com] 
Sent: Thursday, January 05, 2012 4:22 PM
To: Carl Wright
Subject: Re: [sinan] Provide more control over sinan doc results (#65)

I have implemented this carl. I will get it tested and pushed out in the
next couple of days

---

**Comment by CarlWright** [comment]
Eric,

It worked for me. It did work differently than expected. I expected just to feed the options to edoc where the option would identify where to find a the stylesheet. Instead sinan was copying my eg_stylesheet.css to stylesheet.css in the _build directory tree. It worked fine after I figured out what you'd done.

**Comment by ericbmerritt** [comment]
Carl,

 That wasn't actually sinan doing that. It was edoc. Sinan sets the output to the _build/<rel>/lib/<app-vsn>/doc unless you override. I suspect doc copies everything it needs to the output directory.

Eric
