### ISSUE TITLE
Directorys without version suffix

### ISSUE THREAD

**Issue by atlaua** [erlware-deprecated/sinan#84]
When some of the dependencys of sinan are located in directorys in ERL_LIBS, and ERL_LIBS points directly to the directory containing ebin/ and include/, sinan doesn't detect them properly.
Example:
*This way it works:
    ERL_LIBS="/usr/local/getopt
    $ls /usr/local/getopt --> getopt-0.4.3
    $ls /usr/local/getopt/getopt-0.4.3 --> ebin
*This way it doesn't work:
    ERL_LIBS="/usr/local/getopt
    $ls /usr/local/getopt --> ebin

In the latter case, sinan aborts with a message about missing dependencys.

While the latter case might not be a good way to organize his software, it's still done by many people - so maybe sinan should just be generous and also support it.

**Comment by ericbmerritt** [comment]
Atlaua, thanks for the post I will get this resolved.

**Comment by ericbmerritt** [comment]
@atlaua this is supported in the relcool tool (the replacement for sinan's dependency solver. So it wont be fixed here).
