### ISSUE TITLE
sinan failed to bootstrap itself

### ISSUE THREAD

**Issue by talentdeficit** [erlware-deprecated/sinan#91]
trying to build sinan from source, this is the result of `make build`:

`/usr/bin/env erl -noinput -pa /Users/alisdair/Programming/erlang/sinan/_build/sinan/lib/sinan-4.1.1/ebin -s sinan main -extra -s /Users/alisdair/Programming/erlang/sinan -p sinan -n 4.1.1 build
It looks like we couldn't satisfy all the dependency constraints We are going to search the space to see what the problem is but this could take a while
Unable to resolve compile time dependencies, probably due to the following constraints:
 constraint on joxa with constraints [{joxa,"0.0.7a",gte}] originating from these application(s) ['__top_level__'] constraint on getopt with constraints [{getopt,"0.0.1",gte}] originating from these application(s) ['__top_level__'] constraint on erlware_commons with constraints [{erlware_commons,"0.6.0",
                                                  gte}] originating from these application(s) ['__top_level__'] constraint on cucumberl with constraints [{cucumberl,"0.0.4",gte}] originating from these application(s) ['__top_level__'] constraint on sinan with constraints [{sinan,"4.1.1"}] originating from these application(s) ['__top_level__']
make: *** [build] Error 101`

here's my currently installed versions of those dependencies:

``` erlang
1> code:lib_dir(joxa).
"/Users/alisdair/.erlenv/releases/r15b01/lib/erlang/lib/joxa-0.0.8a"
2> code:lib_dir(cucumberl).
"/Users/alisdair/.erlenv/releases/r15b01/lib/erlang/lib/cucumberl-0.0.5"
3> code:lib_dir(getopt).   
"/Users/alisdair/.erlenv/releases/r15b01/lib/erlang/lib/getopt-0.4.2"
4> code:lib_dir(erlware_commons).
"/Users/alisdair/.erlenv/releases/r15b01/lib/erlang/lib/erlware_commons-0.6.1"
```

**Comment by ericbmerritt** [comment]
Do you have proper somewhere there as well? https://github.com/manopapad/proper it should be in the deps.tar.gz

btw, this is something I am actively working on making a lot better.

**Comment by talentdeficit** [comment]
proper is installed too:

``` erlang
1> code:lib_dir(proper).
"/Users/alisdair/.erlenv/releases/r15b01/lib/erlang/lib/proper-1.0"
```

running `sinan -v depends` shows that the lib dir is included when searching for deps

**Comment by ericbmerritt** [comment]
and sgte, which I just realized in not include in the deps bundle and is a new dependency. I will add this to the dep bundle in just a second. but take a look and see if it is there

**Comment by ericbmerritt** [comment]
I have updated the deps.tar.gz with sgte. Let me know if this fixes your issue (https://github.com/downloads/erlware/sinan/deps.tar.gz).

**Comment by talentdeficit** [comment]
adding sgte does not solve the issue

**Comment by ericbmerritt** [comment]
Ok time to look at the non obvious issues then. 

What does code:lib_dir() (it should give you "/Users/alisdair/.erlenv/releases/r15b01/lib/erlang/lib" and I expect it does but I want to make sure that I am not missing anything.

Here are all of the dependencies for sinan the vast majority of these are built in erlang apps. However lets make sure they are all there and I will try to fast track getting the better deps messages out. 

kernel, stdlib, compiler, erlware_commons,
edoc, syntax_tools, eunit, proper, tools,
xmerl, mnesia, erlware_commons,
cucumberl, joxa,
parsetools, getopt

**Comment by talentdeficit** [comment]
problem resolved, i was lacking xmerl. thanks!

**Comment by ericbmerritt** [comment]
Ok. this is more reason to build in better error messages.
