### ISSUE TITLE
Provide .tar.gz of latest sinan release.

### ISSUE THREAD

**Issue by tmcgilchrist** [erlware-deprecated/sinan#93]
I'm putting together a Formula for Homebrew to install sinan.

It'd be great if the downloads page pointed to the latest sinan release with a tar.gz extension and the version number in the filename. Currently the page has a `sinan` link which doesn't include this information and appears to do some `funky` redirecting which confuses Homebrew.

Using the older sinan-4.0.0.tar.gz link works perfectly.

Cheers.

**Comment by ericbmerritt** [comment]
Done. The current 'sinan' was just the escript directly uploaded. I am not sure what github was doing there that caused problems. However, no matter. There is a tarball for the current release now and I will do that in the future as I make releases.

**Comment by tmcgilchrist** [comment]
Thanks.
